# Generated by Django 4.2 on 2023-04-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='curency',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Uzs'), ('USD', 'Usd')], default='UZS', max_length=5, verbose_name='Currency type'),
        ),
    ]
