# Generated by Django 4.2 on 2023-04-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_curency_product_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='customisation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manucaturer',
        ),
        migrations.AddField(
            model_name='product',
            name='customization',
            field=models.CharField(default=1, max_length=255, verbose_name='Customization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=1, max_length=255, verbose_name='Manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'UZD')], default='UZS', max_length=5, verbose_name='Currency type'),
        ),
    ]
