# Generated by Django 4.2 on 2023-04-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options_cart_status_and_more'),
    ]

    operations = [
    ]
