# Generated by Django 4.2 on 2023-04-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_session_key_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ORDERED', 'Ordered')], default='NEW', max_length=10, verbose_name='Cart status type'),
        ),
    ]
