# Generated by Django 4.2 on 2023-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ORDERED', 'Ordered')], default='NEW', max_length=10, verbose_name='Cart status'),
        ),
    ]
