# Generated by Django 4.2 on 2023-04-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_remove_product_customisation_and_more'),
        ('wish', '0003_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'WishList', 'verbose_name_plural': 'WishLists'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'WishListItem', 'verbose_name_plural': 'WishListItems'},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
    ]
