# Generated by Django 4.2 on 2023-04-18 11:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENT", "Percent"), ("FIXED", "Fixed")],
                        default="PERCENT",
                        max_length=25,
                        verbose_name="Sales type",
                    ),
                ),
                (
                    "amount_discount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Amount discount"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Minimal amount",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Is available?"),
                ),
                (
                    "expired_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expired date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Order id"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full name"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="UZ",
                        unique=True,
                        verbose_name="Phone number",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Note")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROCESS", "In-process"),
                            ("ACCEPTED", "Accepted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NEW",
                        max_length=10,
                        verbose_name="Order status",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                            ("UZUM_BANK", "Uzum Bank"),
                        ],
                        default="CASH",
                        max_length=10,
                        verbose_name="Payment type",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_orders",
                        to="cart.cart",
                        verbose_name="Cart",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_orders",
                        to="order.coupon",
                        verbose_name="Coupon",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_district",
                        to="common.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_region",
                        to="common.region",
                        verbose_name="Region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
