# Generated by Django 4.2 on 2023-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], default='PERCENT', max_length=25, verbose_name='Discount type'),
        ),
    ]
