# Generated by Django 4.2 on 2023-04-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_cartitem_quantity"),
        ("order", "0003_alter_order_phone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("cart", "coupon")},
        ),
    ]
